### ISSUE TITLE
AssetManager: Can't Add Custom Asset Loader over Existing Asset Loader

### ISSUE THREAD

**Issue by captkirk88** [craftworkgames/Astrid.Framework#4]
There is an exception being thrown when trying to register a custom Texture loader into the AssetManager of a barebones GameBase.  It tells me that is a no no.  That kinda defeats the purpose of what I was wanting was more control over the texture loading.  I am going to be making a pull request to allow that customization.  Also plan to make a pull request for more settings.  The configuration options you can kinda count on one hand or am I wrong?  Something like GraphicsDevice.PreparingDeviceSettings where you can set the FPS limit and AntiAliasing level would be handy and conform to the somewhat XNAish way you have designed Astrid.

**Comment by craftworkgames** [comment]
Hey @captkirk88 

I built Astrid by myself, in my spare time, over about 6 months. Yes, it's a little bare bones on the options, please forgive me. I've basically only built what I've needed for my own projects. I haven't added anything new recently, but I'm still using Astrid in my own projects so it's still "active" in that sense.

I tried for months to get some help with the project. It turns out making an open source project successful can be pretty darn hard. It's a LOT more work than simply putting to code online.

Astrid has some similarities to XNA / MonoGame but a lot of the inspiration came from LibGDX and my own ideas. I believe Astrid is a better design overall, even though it's not as mature. I'll continue to use Astrid for the foreseeable future regardless.

Anyway, that's the gist of the story. I welcome your pull requests. It'd be nice to have someone to discuss things with, rather than trying to do it all on my own. I'd be interested to know what you're doing with it and other ideas you might have?
